grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3
model_selection:
  module_0:
    class: XGBRegressor
    module: xgboost
    params:
      min_child_weight: 5
      max_depth: 3
    search_param_grid:
      min_child_weight:
      - 1
      - 3
      - 5
      max_depth:
      - 3
      - 10
      - 2
      
  module_1:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      max_depth: 10
      max_features: sqrt
      n_estimators: 3
    search_param_grid:
      max_depth:
      - 10
      - 15
      - 20
      max_features:
      - sqrt
      - log2
      n_estimators:
      - 10
      - 50
      - 100